
version: "3"

services:
  app:
    command: >
      sh -c "
          sleep 10 &&  
          alembic upgrade head&&
          uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
    ports:
      - "5433:5432"

  bot:
    build: .
    command: python /app/bioinformatic_part.py
    volumes:
      - .:/app

volumes:
  postgres_data:
