version: "3"

services:
  app:
    command: >
      sh -c "
          sleep 10 &&  
          uvicorn main:app --reload"
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE_NAME
    ports:
      - "5433:5432"

  bot:
    build: .
    command: python /app/services/bot.py
    volumes:
      - .:/app

volumes:
  postgres_data: