"""Add_3

Revision ID: 4f6cb3aea0cb
Revises: 
Create Date: 2024-06-25 20:38:50.862475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6cb3aea0cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_telegram_key', 'users', type_='unique')
    op.drop_column('users', 'telegram')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_telegram_key', 'users', ['telegram'])
    # ### end Alembic commands ###
